config/routes.rb
Rails.application.routes.draw do
  get 'search_flights', to: 'flights#search'

  resources :flights, only: [:index, :show]
  resources :bookings

  root to: "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'destination_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  
  has_many :passenger_bookings
  has_many :passengers, through: :passenger_bookings
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure, class_name: 'Airport'
  belongs_to :destination, class_name: 'Airport'

  has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  validates :name, :email, presence: true

  has_many :passenger_bookings
  has_many :bookings, through: :passenger_bookings
end

app/models/passenger_booking.rb
class PassengerBooking < ApplicationRecord
  belongs_to :passenger
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find_by(id: params[:id])
    @flight = Flight.includes(:departure, :destination).find(@booking.flight_id)
    @passenger_bookings = PassengerBooking.where("booking_id LIKE ?", @booking.id)
    @passengers = find_passengers(@passenger_bookings)
  end

  def new
    @booking = Booking.new
    @flight = Flight.includes(:departure, :destination).find(params[:flight_id])
    @passengers = params[:passengers].to_i
    @booking.passengers.build
  end

  def create
    @booking = Booking.new(booking_params)
    @flight = Flight.includes(:departure, :destination).find(params[:booking][:flight_id].to_i)

    if @booking.save
      flash[:success] = "Flight booked successfully!"
      redirect_to @booking
    else
      flash.now[:error] = "The flight booking could not be submitted, please refresh the page"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def find_passengers(passenger_bookings)
    passengers = []

    passenger_bookings.each do |record|
      passengers << Passenger.find(record.passenger_id).name
    end

    passengers
  end

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.includes(:departure, :destination).all
  end

  def show
    @flight = Flight.includes(:departure, :destination).find_by(id: params[:id])
  end

  def search
    departure = params[:departure]
    destination = params[:destination]

    @flights = Flight.where("departure_id LIKE ? AND destination_id LIKE ?", "%#{departure}%", "%#{destination}%")

    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Book Flight</h1>

<div style="padding-left: 1rem; border: 1px solid black;">
  <div style="display: flex; gap: 1rem;">
    <p style="margin-bottom: 0;">Departing from: <strong><%= @flight.departure.name %></strong></p>
    <p style="margin-bottom: 0;">Destination: <strong><%= @flight.destination.name %></strong></p>
  </div>
  <p>Duration: <strong><%= @flight.duration %>hrs</strong></p>
  <p>Flight Date: <strong><%= @flight.date.to_date %></strong></p>
</div><br>

<%= form_with model: @booking do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation" style="color: red;">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag 'booking[flight_id]', params[:flight_id] %>

  <h2>Passenger info</h2>
  <% params[:passengers].to_i.times do %>
    <%= f.fields_for :passengers do |passenger| %>
      <div>
        <div>
          <%= passenger.label :name %>
          <%= passenger.text_field :name %>
        </div><br>

        <div>
          <%= passenger.label :email %>
          <%= passenger.text_field :email %>
        </div><br>
      </div><br>
    <% end %>
  <% end %>
  
  <%= f.submit "Book Flight" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booked Flight</h1>

<div style="padding-left: 1rem; border: 1px solid black;">
  <div style="display: flex; gap: 1rem;">
    <p style="margin-bottom: 0;">Departing from: <strong><%= @flight.departure.name %></strong></p>
    <p style="margin-bottom: 0;">Destination: <strong><%= @flight.destination.name %></strong></p>
  </div>
  <p>Duration: <strong><%= @flight.duration %>hrs</strong></p>
  <p>Flight Date: <strong><%= @flight.date.to_date %></strong></p>
</div><br>

<h2><strong>Passengers:</strong></h2>
<ul>
  <% @passengers.each do |passenger| %>
    <li><%= passenger %></li>
  <% end %>
</ul>

app/views/flights/index.html.erb
<h1>Flight Booker</h1>

<%= form_with(url: search_flights_path, method: :get) do |f| %>
  <%= f.label :departure, "Departing from:" %>
  <%= f.collection_select :departure, Airport.order(:id), :id, :name, { selected: params[:departure]} %><br>

  <%= f.label :destination, "Arriving at:" %>
  <%= f.collection_select :destination, Airport.order(:id), :id, :name, { selected: params[:destination]} %><br>

  <%= f.submit 'Search' %>
<% end %>

<h2>Available Flights</h2><hr>

<% @flights.each do |flight| %>
  <div style="padding-left: 1rem; border: 1px solid black;">
    <div style="display: flex; gap: 1rem;">
      <p style="margin-bottom: 0;">Departing from: <strong><%= flight.departure.name %></strong></p>
      <p style="margin-bottom: 0;">Destination: <strong><%= flight.destination.name %></strong></p>
    </div>
    <p>Duration: <strong><%= flight.duration %>hrs</strong></p>
    <p>Flight Date: <strong><%= flight.date.to_date %></strong></p>
    <%= link_to 'view flight', flight_path(flight) %><br><br>
  </div><br>
<% end %>

app/views/flights/show.html.erb
<h1>Flight Details</h1>

<p><strong>Departing from:</strong> <%= @flight.departure.name %></p>
<p><strong>Destination:</strong> <%= @flight.destination.name %></p>
<p><strong>Duration:</strong> <%= @flight.duration %>hrs</p>
<p><strong>Flight Date:</strong> <%= @flight.date.to_date %></p>

<%= link_to 'return to flights', root_path %><br><br>

<%= form_tag new_booking_path, method: :get do %>
  <%= label_tag :passengers, "Select number of passengers:" %>
  <%= select_tag :passengers, options_for_select([1, 2, 3, 4]) %>

  <%= hidden_field_tag :flight_id, @flight.id %>
  <%= submit_tag 'Book flight' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:error] %>
      <div style="color: red; font-size: 1.5rem;"><%= flash[:error] %></div>
    <% end %>
    <% if flash[:success] %>
      <div style="color: green;"><%= flash[:success] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>